[package]
name = "lgl"
version = "0.1.1"
authors = ["Lars Wander <lars.wander@gmail.com>"]
license = "Apache-2.0"
description = "Small directed graph library https://github.com/lwander/lgl"

[dependencies]
